name: buzz
description: Buzz - send vibration signals to your other devices.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  vibration: ^2.0.0
  flutter_foreground_task: ^8.10.4
  wakelock_plus: ^1.2.8
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2

flutter:
  uses-material-design: true
